// <auto-generated />
using System;
using MasterClassProject.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterClassProject.Infrastructure.Migrations
{
    [DbContext(typeof(MasterClass_DbContext))]
    partial class MasterClass_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterClassProject.Domain.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompanyName");

                    b.HasKey("Id");

                    b.ToTable("tblCompany", "Masterclass");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Disney"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Looney Toons"
                        });
                });

            modelBuilder.Entity("MasterClassProject.Domain.Entities.TimeRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2")
                        .HasColumnName("startTime");

                    b.Property<DateTime>("Stop")
                        .HasColumnType("datetime2")
                        .HasColumnName("endTime");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblTimeRegistration", "MasterClass");
                });

            modelBuilder.Entity("MasterClassProject.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("tblUsers", "MasterClass");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CompanyId = 1L,
                            Name = "Mickey Mouse"
                        },
                        new
                        {
                            Id = 2L,
                            CompanyId = 1L,
                            Name = "Minnie Mouse"
                        },
                        new
                        {
                            Id = 3L,
                            CompanyId = 1L,
                            Name = "Donald Duck"
                        },
                        new
                        {
                            Id = 4L,
                            CompanyId = 1L,
                            Name = "Daisy Duck"
                        },
                        new
                        {
                            Id = 5L,
                            CompanyId = 1L,
                            Name = "Goofy"
                        },
                        new
                        {
                            Id = 6L,
                            CompanyId = 2L,
                            Name = "Bugs Bunny"
                        },
                        new
                        {
                            Id = 7L,
                            CompanyId = 2L,
                            Name = "Daffy Duck"
                        },
                        new
                        {
                            Id = 8L,
                            CompanyId = 2L,
                            Name = "Wile E. Coyote"
                        },
                        new
                        {
                            Id = 9L,
                            CompanyId = 2L,
                            Name = "Tweety Bird"
                        },
                        new
                        {
                            Id = 10L,
                            CompanyId = 2L,
                            Name = "Sylvester The Cat"
                        });
                });

            modelBuilder.Entity("MasterClassProject.Domain.Entities.TimeRegistration", b =>
                {
                    b.HasOne("MasterClassProject.Domain.Entities.User", "User")
                        .WithMany("TimeRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MasterClassProject.Domain.Entities.User", b =>
                {
                    b.HasOne("MasterClassProject.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MasterClassProject.Domain.Entities.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MasterClassProject.Domain.Entities.User", b =>
                {
                    b.Navigation("TimeRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
